name: note_gm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Atualizado para a versão mais recente do Flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.17.0 # A versão mais recente compatível com a versão do Flutter
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.3.3
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  font_awesome_flutter: ^10.8.0

flutter:
  uses-material-design: true

